name: Build-Test ZeCalculator Ubuntu
on:
  push:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout ZeCalculator
        uses: actions/checkout@v3

      - name: Install meson and ninja
        run: sudo apt install meson ninja-build

      - name: Setup meson build folder
        run: meson setup build -D test=true -D b_sanitize=address,undefined

      - name: Compile code (GCC)
        run: cd build && meson compile

      - name: Test code (GCC)
        run: cd build && meson test
