name: Build-Test ZeCalculator Ubuntu
on:
  push:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ZeCalculator
        uses: actions/checkout@v3

      - name: Install meson and ninja
        run: pip install meson ninja

      - name: Setup meson build folder
        run: meson setup build -D test=true -D b_sanitize=address,undefined
        env:
          CC: "gcc-13"
          CXX: "g++-13"

      - name: Compile code (GCC)
        run: cd build && meson compile

      - name: Test code (GCC)
        run: cd build && meson test
