name: Build & Test ZeCalculator on Ubuntu (GCC)
on:
  push:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout ZeCalculator
        uses: actions/checkout@v3

      - name: Enable gcc testing repo
        run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

      - name: Install dependencies
        run: sudo apt install meson cmake g++-15

      - name: Setup meson build folder (GCC)
        run: CXX=g++-15 meson setup build -D test=true -D b_sanitize=address,undefined

      - name: Compile code (GCC)
        run: cd build && meson compile

      - name: Test code (GCC)
        run: cd build && meson test
