name: Build & Test ZeCalculator on Ubuntu (GCC)
on:
  push:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout ZeCalculator
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt install meson cmake

      - name: Setup meson build folder (GCC)
        run: meson setup build -D test=true -D b_sanitize=address,undefined

      - name: Compile code (GCC)
        run: cd build && meson compile

      - name: Test code (GCC)
        run: cd build && meson test
